Added data files
FACN3/Water-you-talking-about pull request #31
Opened 2018-02-11 11:39 UTC by SamiSha99

Related to #15 

Let's try this again.

2018-02-11 11:54 UTC, Karyum commented
@SamiSha99 slow down i want you read the issue of the data file ok ? then check the pull request you just made is it correct or not correct depending on the issue?

2018-02-11 13:15 UTC, Amirk390 requested changes

2018-02-11 13:15 UTC, Amirk390 commented on src/App.jsx
> +import { Switch, BrowserRouter } from 'react-router-dom';
Removed any changes that has been made to a file that is not data please

2018-02-11 14:06 UTC, Amirk390 approved these changes
Looks good :100:

2018-02-12 11:05 UTC, matthewdking reviewed
@SamiSha99  In the design there is 6 activities and here you have 5 data items are you sure youre not missing an activity ?

2018-02-12 12:08 UTC, SamiSha99 commented
@matthewdking In the design there is 5 activities not 6, if you consider the flush size then it is considered an activity of 6, in that case, should I add the big flush as an activity?

2018-02-12 12:33 UTC, matthewdking commented
@SamiSha99 I am looking at the prototype and can see six different types of activity

2018-02-12 12:48 UTC, matthewdking requested changes

2018-02-12 12:48 UTC, matthewdking commented on src/NavBar.jsx
> +>>>>>>> master
This should not be here!

2018-02-12 12:53 UTC, Amirk390 approved these changes
Looks good :+1: 
I see no conflict any more and the data looks ok

2018-02-12 13:05 UTC, matthewdking approved these changes
Nice :white_check_mark:

2018-02-12 13:05 UTC, merged